version: '3'

services:
  api:
    image: dokazovi_sb_fe
    container_name: dokazovi_sb_fe
    ports:
      - '3000'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '5'
